/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#111413",
        "on-tertiary-container": "#a60010",
        "secondary-container": "#444746",
        "on-surface-variant": "#bccabb",
        "primary-container": "#4ade80",
        "on-error": "#690005",
        "primary": "#6bfb9a",
        "on-secondary": "#2e3130",
        "surface-bright": "#373a38",
        "on-primary": "#003919",
        "surface-container-highest": "#333534",
        "tertiary-container": "#ffb0a8",
        "outline": "#869486",
        "surface-container-lowest": "#0c0f0d",
        "on-secondary-fixed": "#191c1b",
        "tertiary-fixed-dim": "#ffb4ab",
        "on-secondary-fixed-variant": "#444746",
        "secondary-fixed-dim": "#c5c7c5",
        "secondary-fixed": "#e1e3e1",
        "surface-variant": "#333534",
        "on-surface": "#e2e3e0",
        "surface-container-low": "#191c1b",
        "secondary": "#c5c7c5",
        "error-container": "#93000a",
        "inverse-primary": "#006d36",
        "inverse-surface": "#e2e3e0",
        "primary-fixed-dim": "#4de082",
        "on-tertiary-fixed": "#410002",
        "outline-variant": "#3d4a3e",
        "on-primary-fixed": "#00210c",
        "on-secondary-container": "#b3b6b4",
        "on-primary-container": "#005e2d",
        "error": "#ffb4ab",
        "surface-container-high": "#282b29",
        "surface-tint": "#4de082",
        "on-background": "#e2e3e0",
        "tertiary-fixed": "#ffdad6",
        "background": "#111413",
        "surface-container": "#1d201f",
        "inverse-on-surface": "#2e312f",
        "on-primary-fixed-variant": "#005227",
        "tertiary": "#ffd7d2",
        "primary-fixed": "#6dfe9c",
        "on-tertiary-fixed-variant": "#93000c",
        "surface": "#111413",
        "on-tertiary": "#690006",
        "on-error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}